In [2]:
print("Hello")

Hello


In [3]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [5]:
print(torch.__version__)

2.2.1+cu121


In [6]:
##Introduction to Tensors

##Creating Tensors

In [7]:
scalar = torch.tensor(7)

In [8]:
scalar

tensor(7)

In [9]:
#dimension of that tensor
scalar.ndim

0

In [10]:
### Random Tensors

In [11]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(1,3,3)
random_tensor

tensor([[[0.9962, 0.7937, 0.7913],
         [0.9887, 0.2507, 0.5807],
         [0.3323, 0.4601, 0.4556]]])

In [12]:
random_image_size_tensor = torch.rand(size = (3 , 224 , 224)) # height , width , colour channels (R,G,B)
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [13]:
#create a tensor of all zeros
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
#create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
### Creating a range of tensors or tensors like

#Use torch.range() and get deprecated message , use torch.arange()
torch.arange(1,10)

<ipython-input-15-bb1c83ddf295>:4: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
one_to_ten = torch.arange(start = 0,end = 100 , step = 10)
one_to_ten

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
#Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
#Tensors DataTypes